"""phase2 initial schema: user, anime, genre, studio, episode

Revision ID: 041fd802d0c8
Revises: 
Create Date: 2026-09-04 04:24:26.891649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '041fd802d0c8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anime',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anilist_id', sa.Integer(), nullable=True),
    sa.Column('mal_id', sa.Integer(), nullable=True),
    sa.Column('kitsu_id', sa.Integer(), nullable=True),
    sa.Column('simkl_id', sa.Integer(), nullable=True),
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('imdb_id', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('english_title', sa.String(length=500), nullable=True),
    sa.Column('native_title', sa.String(length=500), nullable=True),
    sa.Column('romaji_title', sa.String(length=500), nullable=True),
    sa.Column('synopsis', sa.Text(), nullable=True),
    sa.Column('poster_url', sa.String(length=1024), nullable=True),
    sa.Column('banner_url', sa.String(length=1024), nullable=True),
    sa.Column('trailer_url', sa.String(length=1024), nullable=True),
    sa.Column('format', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('season', sa.String(length=20), nullable=True),
    sa.Column('season_year', sa.Integer(), nullable=True),
    sa.Column('episodes', sa.Integer(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('source_material', sa.String(length=50), nullable=True),
    sa.Column('score', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('popularity', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('favourites_count', sa.Integer(), nullable=True),
    sa.Column('country_of_origin', sa.String(length=10), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anime_anilist_id'), 'anime', ['anilist_id'], unique=True)
    op.create_index(op.f('ix_anime_kitsu_id'), 'anime', ['kitsu_id'], unique=True)
    op.create_index(op.f('ix_anime_mal_id'), 'anime', ['mal_id'], unique=True)
    op.create_index(op.f('ix_anime_season_year'), 'anime', ['season_year'], unique=False)
    op.create_index(op.f('ix_anime_simkl_id'), 'anime', ['simkl_id'], unique=True)
    op.create_index(op.f('ix_anime_title'), 'anime', ['title'], unique=False)
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('studios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anilist_id', sa.Integer(), nullable=True),
    sa.Column('mal_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('logo_url', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anilist_id'),
    sa.UniqueConstraint('mal_id')
    )
    op.create_index(op.f('ix_studios_name'), 'studios', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('language_code', sa.String(length=16), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_telegram_user_id'), 'users', ['telegram_user_id'], unique=True)
    op.create_table('anime_genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anime_id', 'genre_id', name='uq_anime_genre')
    )
    op.create_index(op.f('ix_anime_genres_anime_id'), 'anime_genres', ['anime_id'], unique=False)
    op.create_index(op.f('ix_anime_genres_genre_id'), 'anime_genres', ['genre_id'], unique=False)
    op.create_table('anime_studios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('studio_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['studio_id'], ['studios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anime_id', 'studio_id', 'role', name='uq_anime_studio_role')
    )
    op.create_index(op.f('ix_anime_studios_anime_id'), 'anime_studios', ['anime_id'], unique=False)
    op.create_index(op.f('ix_anime_studios_studio_id'), 'anime_studios', ['studio_id'], unique=False)
    op.create_table('anime_titles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('title_type', sa.String(length=20), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('normalized_title', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anime_titles_anime_id'), 'anime_titles', ['anime_id'], unique=False)
    op.create_index(op.f('ix_anime_titles_normalized_title'), 'anime_titles', ['normalized_title'], unique=False)
    op.create_table('episodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('anilist_episode_id', sa.String(length=50), nullable=True),
    sa.Column('kitsu_episode_id', sa.String(length=50), nullable=True),
    sa.Column('episode_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('synopsis', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=1024), nullable=True),
    sa.Column('air_date', sa.Date(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anime_id', 'episode_number', name='uq_anime_episode_number')
    )
    op.create_index(op.f('ix_episodes_anime_id'), 'episodes', ['anime_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_episodes_anime_id'), table_name='episodes')
    op.drop_table('episodes')
    op.drop_index(op.f('ix_anime_titles_normalized_title'), table_name='anime_titles')
    op.drop_index(op.f('ix_anime_titles_anime_id'), table_name='anime_titles')
    op.drop_table('anime_titles')
    op.drop_index(op.f('ix_anime_studios_studio_id'), table_name='anime_studios')
    op.drop_index(op.f('ix_anime_studios_anime_id'), table_name='anime_studios')
    op.drop_table('anime_studios')
    op.drop_index(op.f('ix_anime_genres_genre_id'), table_name='anime_genres')
    op.drop_index(op.f('ix_anime_genres_anime_id'), table_name='anime_genres')
    op.drop_table('anime_genres')
    op.drop_index(op.f('ix_users_telegram_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_studios_name'), table_name='studios')
    op.drop_table('studios')
    op.drop_table('genres')
    op.drop_index(op.f('ix_anime_title'), table_name='anime')
    op.drop_index(op.f('ix_anime_simkl_id'), table_name='anime')
    op.drop_index(op.f('ix_anime_season_year'), table_name='anime')
    op.drop_index(op.f('ix_anime_mal_id'), table_name='anime')
    op.drop_index(op.f('ix_anime_kitsu_id'), table_name='anime')
    op.drop_index(op.f('ix_anime_anilist_id'), table_name='anime')
    op.drop_table('anime')
    # ### end Alembic commands ###
