"""phase5: character, voice_actor, staff models

Revision ID: 469ad62ee400
Revises: 73675596a6dc
Create Date: 2026-09-06 07:57:26.265069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '469ad62ee400'
down_revision: Union[str, None] = '73675596a6dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anilist_id', sa.Integer(), nullable=False),
    sa.Column('name_full', sa.String(length=255), nullable=False),
    sa.Column('name_native', sa.String(length=255), nullable=True),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_characters_anilist_id'), 'characters', ['anilist_id'], unique=True)
    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anilist_id', sa.Integer(), nullable=False),
    sa.Column('name_full', sa.String(length=255), nullable=False),
    sa.Column('name_native', sa.String(length=255), nullable=True),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_anilist_id'), 'staff', ['anilist_id'], unique=True)
    op.create_table('voice_actors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anilist_id', sa.Integer(), nullable=False),
    sa.Column('name_full', sa.String(length=255), nullable=False),
    sa.Column('name_native', sa.String(length=255), nullable=True),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_actors_anilist_id'), 'voice_actors', ['anilist_id'], unique=True)
    op.create_table('anime_characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anime_id', 'character_id', name='uq_anime_character')
    )
    op.create_index(op.f('ix_anime_characters_anime_id'), 'anime_characters', ['anime_id'], unique=False)
    op.create_index(op.f('ix_anime_characters_character_id'), 'anime_characters', ['character_id'], unique=False)
    op.create_table('anime_staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anime_id', 'staff_id', 'role', name='uq_anime_staff_role')
    )
    op.create_index(op.f('ix_anime_staff_anime_id'), 'anime_staff', ['anime_id'], unique=False)
    op.create_index(op.f('ix_anime_staff_staff_id'), 'anime_staff', ['staff_id'], unique=False)
    op.create_table('character_voice_actors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('voice_actor_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voice_actor_id'], ['voice_actors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anime_id', 'character_id', 'voice_actor_id', 'language', name='uq_character_voice_actor')
    )
    op.create_index(op.f('ix_character_voice_actors_anime_id'), 'character_voice_actors', ['anime_id'], unique=False)
    op.create_index(op.f('ix_character_voice_actors_character_id'), 'character_voice_actors', ['character_id'], unique=False)
    op.create_index(op.f('ix_character_voice_actors_voice_actor_id'), 'character_voice_actors', ['voice_actor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_character_voice_actors_voice_actor_id'), table_name='character_voice_actors')
    op.drop_index(op.f('ix_character_voice_actors_character_id'), table_name='character_voice_actors')
    op.drop_index(op.f('ix_character_voice_actors_anime_id'), table_name='character_voice_actors')
    op.drop_table('character_voice_actors')
    op.drop_index(op.f('ix_anime_staff_staff_id'), table_name='anime_staff')
    op.drop_index(op.f('ix_anime_staff_anime_id'), table_name='anime_staff')
    op.drop_table('anime_staff')
    op.drop_index(op.f('ix_anime_characters_character_id'), table_name='anime_characters')
    op.drop_index(op.f('ix_anime_characters_anime_id'), table_name='anime_characters')
    op.drop_table('anime_characters')
    op.drop_index(op.f('ix_voice_actors_anilist_id'), table_name='voice_actors')
    op.drop_table('voice_actors')
    op.drop_index(op.f('ix_staff_anilist_id'), table_name='staff')
    op.drop_table('staff')
    op.drop_index(op.f('ix_characters_anilist_id'), table_name='characters')
    op.drop_table('characters')
    # ### end Alembic commands ###
