"""phase6: user watchlist, favorites, history, ratings

Revision ID: ca90b2a24894
Revises: 469ad62ee400
Create Date: 2026-09-06 15:36:26.486606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca90b2a24894'
down_revision: Union[str, None] = '469ad62ee400'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'anime_id', name='uq_user_favorite')
    )
    op.create_index(op.f('ix_user_favorites_anime_id'), 'user_favorites', ['anime_id'], unique=False)
    op.create_index(op.f('ix_user_favorites_user_id'), 'user_favorites', ['user_id'], unique=False)
    op.create_table('user_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'anime_id', name='uq_user_history')
    )
    op.create_index(op.f('ix_user_history_anime_id'), 'user_history', ['anime_id'], unique=False)
    op.create_index(op.f('ix_user_history_user_id'), 'user_history', ['user_id'], unique=False)
    op.create_table('user_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('rated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 10', name='ck_user_rating_range'),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'anime_id', name='uq_user_rating')
    )
    op.create_index(op.f('ix_user_ratings_anime_id'), 'user_ratings', ['anime_id'], unique=False)
    op.create_index(op.f('ix_user_ratings_user_id'), 'user_ratings', ['user_id'], unique=False)
    op.create_table('user_watchlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'anime_id', name='uq_user_watchlist')
    )
    op.create_index(op.f('ix_user_watchlist_anime_id'), 'user_watchlist', ['anime_id'], unique=False)
    op.create_index(op.f('ix_user_watchlist_user_id'), 'user_watchlist', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_watchlist_user_id'), table_name='user_watchlist')
    op.drop_index(op.f('ix_user_watchlist_anime_id'), table_name='user_watchlist')
    op.drop_table('user_watchlist')
    op.drop_index(op.f('ix_user_ratings_user_id'), table_name='user_ratings')
    op.drop_index(op.f('ix_user_ratings_anime_id'), table_name='user_ratings')
    op.drop_table('user_ratings')
    op.drop_index(op.f('ix_user_history_user_id'), table_name='user_history')
    op.drop_index(op.f('ix_user_history_anime_id'), table_name='user_history')
    op.drop_table('user_history')
    op.drop_index(op.f('ix_user_favorites_user_id'), table_name='user_favorites')
    op.drop_index(op.f('ix_user_favorites_anime_id'), table_name='user_favorites')
    op.drop_table('user_favorites')
    # ### end Alembic commands ###
